### ISSUE TITLE
Autorecord in- & outgoing calls

### ISSUE THREAD

**Issue by Markus0103** [2shrestha22/lineage-call-recording-enabler#3]
Hello, I would like to know if there's a possible way to autorecord all in- and outgoing calls, because you always have to re-enable it for every single call.

**Comment by 2shrestha22** [comment]
We don't have auto record feature in Lineage OS dialer app so it will not be possible to enable using this method. However crDroid dialer app has autorecord feature.

**Comment by Markus0103** [comment]
Oh, thats sad, but good to know, thank you.

**Comment by 2shrestha22** [comment]
@Markus0103 or you can use this https://github.com/chenxiaolong/BCR

**Comment by Markus0103** [comment]
Thank you very much, this works more than perfect for me.
