### ISSUE TITLE
versioning

### ISSUE THREAD

**Issue by IzzySoft** [2shrestha22/lineage-call-recording-enabler#4]
Just wondering: your `module.prop` says it's version 01.1. (versionCode 1), while the latest release is v1.1.0. Is this intentional, or did you just forget to update `module.prop`?

**Comment by 2shrestha22** [comment]
Sorry for that. I forgot to update the `module.prop` file. But it shouldn't affect anything.

**Comment by 2shrestha22** [comment]
I will add a license then you can add it in your repo.

**Comment by IzzySoft** [comment]
Thanks a lot! Please also update `module.prop`, as that's what my updater goes by (checking if `versionCode` was increased) and also where information to display (name, description, versioning) is taken from.

Will you give me a ping when it's there?

**Comment by 2shrestha22** [comment]
Hi @IzzySoft , I have added license and updated the version name.

**Comment by IzzySoft** [comment]
You forgot `versionCode` – that's the one checked against. `version` can be any string, so it's not easily compared against (though I use that one to find the matching ZIP, where the tag name is "calculated" based on it). `versionCode` is an integer which, by definition, must be increased with each release – so a higher `versionCode` always means a newer release. So if that's always `1`, updates would never be fetched (or announced to the user).

So can you take care for that as well? At least with upcoming (future) releases?

**Comment by 2shrestha22** [comment]
Thanks, I will update the version code as well when there is a new release.

**Comment by IzzySoft** [comment]
Great, thanks a lot! Then updates will be recognized automatically by my updater and fetched accordingly. (updater currently is triggered manually about once a day while my repo is "still in beta"; will soon™ be integrated with the daily aut-update-run for my F-Droid repo)
