### ISSUE TITLE
auto recording?

### ISSUE THREAD

**Issue by eramax** [2shrestha22/lineage-call-recording-enabler#5]
Does it just display the record button or does it enable auto recording? If it records automatically, it would be great.

**Comment by 2shrestha22** [comment]
This does not add any added functionality to LineageOS. It just activates the call recording for all country. So it does not enables auto-recording.

**Comment by 2shrestha22** [comment]
You can use BCR if you want auto recording.

**Comment by eramax** [comment]
Thanks so much for your help
