### ISSUE TITLE
call recording not working with this enabler

### ISSUE THREAD

**Issue by llluuuzzziii** [2shrestha22/lineage-call-recording-enabler#6]
The recovery.zip does not work under LOS21 (lineage-21.0-20240820-nightly-FP5-signed). The update in LOS recovery runs without errors, but the recording button does not appear in the dialer when an incoming call is accepted.

**Comment by 2shrestha22** [comment]
Have you tried flashing it again?

**Comment by 2shrestha22** [comment]
@llluuuzzziii Do you still face the issue? I can't reproduce this issue on my device with Lineage 21. We can keep this issue open for now.

**Comment by llluuuzzziii** [comment]
hi,
after the error I used the magisk module and it worked straight away.
I can't help you troubleshooting right now. You can close the issue.
Thanks

**Comment by llluuuzzziii** [comment]
closed
